# Generated by Django 3.1.14 on 2022-01-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jade', '0006_auto_20220109_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='phoneno',
        ),
    ]
