# Generated by Django 3.1.14 on 2021-12-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(choices=[('soldout', 'Sold Out'), ('forsale', 'For Sale')], max_length=200, null=True)),
                ('price', models.FloatField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('ready', 'Ready'), ('noready', 'Not Ready')], max_length=200, null=True)),
                ('category', models.ManyToManyField(to='jade.Category')),
            ],
        ),
    ]
