# Generated by Django 3.1.14 on 2021-12-30 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jade', '0004_auto_20211231_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
