# Generated by Django 3.1.14 on 2022-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jade', '0007_auto_20220101_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
