# Generated by Django 3.1.14 on 2022-01-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jade', '0009_auto_20220103_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
    ]
