# Generated by Django 3.1.14 on 2022-01-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jade', '0011_auto_20220103_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
