# Generated by Django 3.1.14 on 2022-01-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jade1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(choices=[('soldOut', 'Sold Out'), ('forSale', 'For Sale')], max_length=200, null=True)),
                ('price', models.FloatField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('ready', 'Ready'), ('noready', 'Not Ready')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='jade1.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='static/post/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jade1.product')),
            ],
        ),
    ]
