# Generated by Django 3.1.14 on 2022-01-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jade1', '0002_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='post',
            new_name='product',
        ),
    ]
