# Generated by Django 3.2.9 on 2021-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_createed_at_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
